# Generated by Django 5.0.6 on 2024-06-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_moviebacklogitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviebacklogitem",
            name="imdb_rating",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
