# Generated by Django 5.0.6 on 2024-06-20 16:37

import example.fields
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviebacklogitem_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebacklogitem',
            name='id',
            field=example.fields.UUIDAutoField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
