// This file is auto-generated by @hey-api/openapi-ts

export const $AssistantSchema = {
    properties: {
        id: {
            title: 'Id',
            type: 'string'
        },
        name: {
            title: 'Name',
            type: 'string'
        }
    },
    required: ['id', 'name'],
    title: 'AssistantSchema',
    type: 'object'
} as const;

export const $ThreadSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'ID'
        },
        name: {
            anyOf: [
                {
                    maxLength: 255,
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        created_at: {
            format: 'date-time',
            title: 'Created At',
            type: 'string'
        },
        updated_at: {
            format: 'date-time',
            title: 'Updated At',
            type: 'string'
        }
    },
    required: ['created_at', 'updated_at'],
    title: 'ThreadSchema',
    type: 'object'
} as const;

export const $ThreadSchemaIn = {
    properties: {
        name: {
            title: 'Name',
            type: 'string'
        }
    },
    title: 'ThreadSchemaIn',
    type: 'object'
} as const;

export const $ThreadMessageTypeEnum = {
    enum: ['human', 'ai', 'generic', 'system', 'function', 'tool'],
    title: 'ThreadMessageTypeEnum',
    type: 'string'
} as const;

export const $ThreadMessagesSchemaOut = {
    properties: {
        id: {
            title: 'Id',
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/ThreadMessageTypeEnum'
        },
        content: {
            title: 'Content',
            type: 'string'
        }
    },
    required: ['id', 'type', 'content'],
    title: 'ThreadMessagesSchemaOut',
    type: 'object'
} as const;

export const $ThreadMessagesSchemaIn = {
    properties: {
        assistant_id: {
            title: 'Assistant Id',
            type: 'string'
        },
        content: {
            title: 'Content',
            type: 'string'
        }
    },
    required: ['assistant_id', 'content'],
    title: 'ThreadMessagesSchemaIn',
    type: 'object'
} as const;