# Generated by Django 5.0.6 on 2024-06-07 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviebacklogitem",
            options={
                "ordering": ("user", "position"),
                "verbose_name": "Movie Backlog Item",
                "verbose_name_plural": "Movie Backlog Items",
            },
        ),
        migrations.RemoveIndex(
            model_name="moviebacklogitem",
            name="movie_item_created_at_desc",
        ),
        migrations.AddField(
            model_name="moviebacklogitem",
            name="position",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="moviebacklogitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_backlog",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moviebacklogitem",
            unique_together={("user", "imdb_url")},
        ),
    ]
