# Generated by Django 5.0.6 on 2024-05-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="cls_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistant",
            name="openai_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
