# Generated by Django 5.0.6 on 2024-06-04 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_assistant", "0004_remove_message_message_created_at_desc_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
